<MyRoot>:

    random_label:  random_label

    BoxLayout:

        orientation: 'vertical'
        Label:
            text: "Fridgin!"
            font_size: 64
            color: 0.92, 0.45, 0

        Label:
            id: random_label
            text: "-"
            font_size: 64

        Button:
            text: "Let's fridgin go!"
            font_size: 32
            size: 100, 50
            on_press: root.gen_random_number()
